### ISSUE TITLE
Remove "mohist" from the list or add "catserver"

### ISSUE THREAD

**Issue by Rabbit0w0** [KennyTV/list-of-shame#52]
Whatever, mohist is better than catserver because catserver is just stealing code from mohist and magma

**Comment by Andre601** [comment]
mohist still deletes/replaces existing jars with their own ones AND on top of that doesn't even have a vetted/curated place for those for some security.
Like who says that the X devs of those "patched" versions won't insert their own backdoors?

**Comment by Rabbit0w0** [comment]
![image](https://user-images.githubusercontent.com/21006278/123487484-8d314700-d640-11eb-825d-2796599b106d.png)

**Comment by Shawiizz** [comment]
Hello, first, know that every plugins we fix are completely open source on our GitHub organization so that users can check the sources if they want. Then, the plugin patcher is only here to temporarily fix a big plugin used by a lot of users the time we found a way to properly fix it in Mohist directly.
Hope that this help people to understand how this works ^^

**Comment by Andre601** [comment]
[this here](https://github.com/MohistMC/Mohist/blob/70a303f4d02e9480cc5472c1c26f7d9cb6560732/src/fmllauncher/java/com/mohistmc/AutoDeletePlugins.java#L20-L22) tells me a different story to be honest, especially since one class is called PluginMods**Delete**

**Comment by Andre601** [comment]
Also, Hybrid servers in general are shit anyway and shouldn't be used. Forge/Fabric and Bukkit mix as well as Water and Oil.

**Comment by Shawiizz** [comment]
The class has always been called PluginsModsDelete, i don't think the name is really important (if I'm wrong tell me). And the modification to add the repo url in the message is here since EssentialsX team did their page and aurora (a essx team member) explained me what was wrong with the plugin patcher and that it was confusing people. I changed it in this [commit](https://github.com/MohistMC/Mohist/compare/4b98d97f20f8...f1566d4a5284#diff-0d24b179f56b3af28027a28dba50d851448d3ed889a6ca8b6d1a06c2e8576d35).
If you don't like hybrids, okay, no problem, i respect your choice. But trying to destroy the reputation of an open source and free project is not good at all, and it hurts us a lot, know it.

**Comment by JRoy** [comment]
Crying amoungus

![Screenshot_20210622-204426.png](https://user-images.githubusercontent.com/10731363/123492076-6cd49e80-d5e6-11eb-9ec4-a6f7e1e25dc6.png)

**Comment by Romaindu35** [comment]
In addition, currently all plugins that have had modified versions have been fixed in Mohist, as you can see [here](https://github.com/MohistMC/Mohist/blob/1.16.5/src/fmllauncher/java/com/mohistmc/util/AutoDeletePlugins.java), no more plugins are replaced.
As has already been said, this is a **TEMPORARY** solution, while waiting for the bugs to be fixed in Mohist. 
Moreover, the user is informed, and his authorization is requested.
![image](https://user-images.githubusercontent.com/67557705/123512440-c345e980-d687-11eb-9c46-34dffe3e0a42.png)
It has always been the case

**Comment by DaJokni** [comment]
In my opinion, this forge + bukkit mixture makes no sense, and shall stay on the list.

**Comment by Andre601** [comment]
> In my opinion, this forge + bukkit mixture makes no sense, and shall stay on the list.

Yeah. I personally even think that the list should add Hybrid-servers in general.
There is no real need nor reason to try and mix plugins and mods together. It will mess up everything and only makes the lives of devs more difficult.

**Comment by KennyTV** [comment]
If you have someone talking down your project *solely based on this list*, you can call them a breadface and refer them to this message.

The entry will stay, given such a poorly implemented workaround has made its way into such a software, even if only "temporary", especially keeping the security concerns in mind. Just because it *didn't* go wrong doesn't mean it *couldn't* have gone *completely* bonkers. Feel free to pr Catserver or any other even more funky hybrid tho.

Closing this before everything starts to go up in flames
